apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-fnb-admin-corp-app-0
  namespace: fnb-msa-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---

