apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs--app-0
  namespace: {namespace-name}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---

