---
apiVersion: v1
kind: Service
metadata:
  name: {service-name}
  namespace: {namespace-name}
  labels:
    app: {app-name}
spec:
  selector:
    app: {app-name}
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {app-name}
  namespace: {namespace-name}
  labels:
    app: {app-name}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {app-name}
  template:
    metadata:
      labels:
        app: {app-name}
    spec:
      containers:
      - name: {container-name}
        image: {repository}
        ports:
          - name: http
            containerPort: 8080
        readinessProbe: 
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 1
        startupProbe: 
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 40
          failureThreshold: 1
        resources:
          requests:
            memory: 3.5Gi
          limits:
            memory: 3.5Gi
      terminationGracePeriodSeconds: 90
      imagePullSecrets:
        - name: regcred
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {app-name}
              topologyKey: kubernetes.io/hostname
