apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File      parsers.conf
        HTTP_Server       On
        HTTP_Listen       0.0.0.0
        HTTP_Port         2020
    [INPUT]
        Name              tail
        Path              /var/log/containers/a-app-*.log
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     10MB
        Refresh_Interval  10
        Tag               a-app.*
        parser            docker
    [FILTER]
        Name              kubernetes
        Match             a-app.*
        Kube_URL          https://kubernetes.default.svc:443
        Kube_CA_File      /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File   /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix   kube.var.log.containers.
        Merge_Log         On
        Merge_Log_Key     log_processed
        Regex_Parser      kube-custom
    [OUTPUT]
        Name              kinesis_firehose
        Match             a-app.*
        region            ap-northeast-2
        delivery_stream   kinesis-index-name
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-30T05:43:33Z"
  labels:
    k8s-app: fluent-bit
  name: fluent-bit
  namespace: logging
