apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File      parsers.conf
        HTTP_Server       On
        HTTP_Listen       0.0.0.0
        HTTP_Port         2020
    [INPUT]
        Name              tail
        Path              /var/log/containers/fnb-admin-app-*.log
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     10MB
        Refresh_Interval  10
        Tag               fnb-admin-app.*
        multiline.parser  docker, cri
    [FILTER]
        Name              kubernetes
        Match             fnb-admin-app.*
        Kube_URL          https://kubernetes.default.svc:443
        Kube_CA_File      /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File   /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix   kube.var.log.containers.
        Merge_Log         On
        Merge_Log_Key     log_processed
        Regex_Parser      kube-custom
    [OUTPUT]
        Name              kinesis_firehose
        Match             fnb-admin-app.*
        region            ap-northeast-2
        delivery_stream   prod-fnb-admin-log
    [INPUT]
        Name              tail
        Tag               fnb-admin-corp-app.*
        Path              /var/log/containers/fnb-admin-corp-app-*.log
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     10MB
        Refresh_Interval  10
        multiline.parser  docker, cri
    [FILTER]
        Name              kubernetes
        Match             fnb-admin-corp-app.*
        Kube_URL          https://kubernetes.default.svc:443
        Kube_CA_File      /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File   /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix   kube.var.log.containers.
        Merge_Log         On
        Merge_Log_Key     log_processed
        Regex_Parser      kube-custom
    [OUTPUT]
        Name              kinesis_firehose
        Match             fnb-admin-corp-app.*
        region            ap-northeast-2
        delivery_stream   prod-fnb-admin-corp-log
    [INPUT]
        Name              tail
        Path              /var/log/containers/fnb-api-app-*.log
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     10MB
        Refresh_Interval  10
        Tag               fnb-api-app.*
        multiline.parser  docker, cri
    [FILTER]
        Name              kubernetes
        Match             fnb-api-app.*
        Kube_URL          https://kubernetes.default.svc:443
        Kube_CA_File      /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File   /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix   kube.var.log.containers.
        Merge_Log         On
        Merge_Log_Key     log_processed
        Regex_Parser      kube-custom
    [OUTPUT]
        Name              kinesis_firehose
        Match             fnb-api-app.*
        region            ap-northeast-2
        delivery_stream   prod-fnb-api-log
  parsers.conf: |
    [PARSER]
        Name              docker
        Format            json
        Time_Key          time
        Time_Format       %Y-%m-%dT%H:%M:%S.%L
        Time_Keep         On
        # Command       | Decoder   | Field | Optional Action   |
        # ==============|===========|=======|===================|
        Decode_Field_As   json       log
    [PARSER]
      # http://rubular.com/r/tjUt3Awgg4
        Name              cri
        Format            regex
        Regex             ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key          time
        Time_Format       %Y-%m-%dT%H:%M:%S.%L%z
    [PARSER]
        Name              kube-custom
        Format            regex
        Regex             (?<tag>[^.]+)?\.?(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$

kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-30T05:43:33Z"
  labels:
    k8s-app: fluent-bit
  name: fluent-bit
  namespace: logging
